const DEFAULT_MARKET = [
  {
    id: 1,
    name: "iPhone Pro",
    desc: "Premium smartfon, 256GB xotira",
    price: 10000,
    image: "market/iphone.png",
    bought: false,
    category: "Elektronika",
  },
  {
    id: 2,
    name: "MacBook Air",
    desc: "Yengil va kuchli noutbuk, M2 chip",
    price: 22000,
    image: "market/macbook.png",
    bought: false,
    category: "Elektronika",
  },
  {
    id: 3,
    name: "AirPods Pro",
    desc: "Sifatli simsiz naushniklar",
    price: 5000,
    image: "market/airpods.png",
    bought: false,
    category: "Elektronika",
  },
  {
    id: 4,
    name: "Logitech Sichqoncha",
    desc: "Ergonomik simsiz sichqoncha",
    price: 1000,
    image: "https://resource.logitech.com/w_692,c_limit,q_auto,f_auto,dpr_1.0/d_transparent.gif/content/dam/logitech/en/products/mice/mx-master-3s/gallery/mx-master-3s-mouse-top-view-graphite.png",
    bought: false,
    category: "Aksessuar",
  },
  {
    id: 5,
    name: "IsoUz Futbolkasi",
    desc: "IsoUz brend futbolka, sifatli mato",
    price: 400,
    image: "market/futbolka.png",
    bought: false,
    category: "Kiyim",
  },
  {
    id: 6,
    name: "IsoUz Ruchkasi",
    desc: "Brendli metal ruchka",
    price: 30,
    image: "market/ruchka.png",
    bought: false,
    category: "Konstovar",
  },
  {
    id: 7,
    name: "IsoUz Daftari",
    desc: "A5 o'lchamdagi brendli daftar",
    price: 50,
    image: "market/daftar.png",
    bought: false,
    category: "Konstovar",
  },
  {
    id: 8,
    name: "Termos (500ml)",
    desc: "Suyuqlik haroratini saqlaydi",
    price: 200,
    image: "market/termos.png",
    bought: false,
    category: "Kundalik",
  },
  {
    id: 9,
    name: "Keychron K2",
    desc: "Mexanik RGB klaviatura",
    price: 1500,
    image: "market/keyboard.png",
    bought: false,
    category: "Elektronika",
  },
  {
    id: 10,
    name: "USB-C Hub",
    desc: "7-in-1 ko'p funksiyali hub",
    price: 700,
    image: "market/usb.png",
    bought: false,
    category: "Aksessuar",
  },
  {
    id: 11,
    name: "IsoUz Kepkasi",
    desc: "Premium materialdan kepka",
    price: 300,
    image: "market/kepka.png",
    bought: false,
    category: "Kiyim",
  },
  {
    id: 12,
    name: "Mousepad XL",
    desc: "Katta va mayin gaming mousepad",
    price: 150,
    image: "https://images.unsplash.com/photo-1616763355548-1b606f439f86?w=400",
    bought: false,
    category: "Aksessuar",
  },
];

export default DEFAULT_MARKET;
