const DEFAULT_STUDENTS = [
  {
    id: 1,
    familya: "Alimov",
    name: "Sardor Alimov",
    login: "sardor",
    password: "12345",
    email: "sardor@isouz.com",
    phone: "+998 90 123 45 67",
    avatar: "S",
    color: "#6366f1",
    coin: 850,
    groups: [
      {
        id: 1,
        direction: "Frontend",
        name: "JavaScript Bootcamp",
        teacher: "Azizov Farhod",
        start: "01.02.2026",
        end: "01.08.2026",
        status: "active",
      },
      {
        id: 2,
        direction: "SMM",
        name: "SMM Pro",
        teacher: "Dilnoza Yusupova",
        start: "15.01.2026",
        end: "15.07.2026",
        status: "active",
      },
    ],
    weeklyProgress: [85, 40, 95, 60, 100, 75, 15],
    payments: [
      {
        id: 1,
        amount: 800000,
        status: "paid",
        method: "Click",
        date: "2026-03-05 09:30",
        group: "JavaScript Bootcamp",
      },
      {
        id: 2,
        amount: 1000000,
        status: "paid",
        method: "Naqd",
        date: "2026-04-05 10:00",
        group: "SMM Pro",
      },
    ],
  },
  {
    id: 2,
    familya: "Karimova",
    name: "Aziza Karimova",
    login: "aziza",
    password: "12345",
    email: "aziza@isouz.com",
    phone: "+998 91 234 56 78",
    avatar: "A",
    color: "#f59e0b",
    coin: 720,
    groups: [
      {
        id: 1,
        direction: "Frontend",
        name: "Frontend 301",
        teacher: "Akmal Karimov",
        start: "01.03.2026",
        end: "01.09.2026",
        status: "active",
      },
    ],
    weeklyProgress: [45, 70, 30, 90, 55, 80, 20],
    payments: [
      {
        id: 1,
        amount: 800000,
        status: "paid",
        method: "Naqd",
        date: "2026-02-12 10:30",
        group: "Frontend 301",
      },
    ],
  },
  {
    id: 3,
    familya: "Toshmatov",
    name: "Bobur Toshmatov",
    login: "bobur",
    password: "12345",
    email: "bobur@isouz.com",
    phone: "+998 93 345 67 89",
    avatar: "B",
    color: "#ef4444",
    coin: 560,
    groups: [
      {
        id: 1,
        direction: "Frontend",
        name: "JavaScript Bootcamp",
        teacher: "Akmal Karimov",
        start: "01.02.2026",
        end: "01.08.2026",
        status: "active",
      },
      {
        id: 2,
        direction: "Backend",
        name: "Python 101",
        teacher: "Jasur Nazarov",
        start: "01.01.2026",
        end: "01.07.2026",
        status: "active",
      },
      {
        id: 3,
        direction: "Marketing",
        name: "Marketing Pro",
        teacher: "Dilnoza Yusupova",
        start: "01.02.2026",
        end: "01.08.2026",
        status: "active",
      },
    ],
    payments: [
      {
        id: 1,
        amount: 400000,
        status: "paid",
        method: "Click",
        date: "2026-01-15 18:30",
        group: "Python 101",
      },
    ],
  },
  {
    id: 4,
    familya: "Rahimov",
    name: "Jasur Rahimov",
    login: "jasur",
    password: "12345",
    email: "jasur@isouz.com",
    phone: "+998 94 456 78 90",
    avatar: "J",
    color: "#10b981",
    coin: 980,
    groups: [
      {
        id: 1,
        direction: "Frontend",
        name: "JavaScript Bootcamp",
        teacher: "Akmal Karimov",
        start: "01.02.2026",
        end: "01.08.2026",
        status: "active",
      },
    ],
    payments: [
      {
        id: 1,
        amount: 800000,
        status: "paid",
        method: "Payme",
        date: "2026-02-01 11:00",
        group: "JavaScript Bootcamp",
      },
    ],
  },
  {
    id: 5,
    familya: "Umarova",
    name: "Malika Umarova",
    login: "malika",
    password: "12345",
    email: "malika@isouz.com",
    phone: "+998 95 567 89 01",
    avatar: "M",
    color: "#8b5cf6",
    coin: 640,
    groups: [
      {
        id: 2,
        direction: "Frontend",
        name: "JavaScript Bootcamp",
        teacher: "Akmal Karimov",
        start: "01.02.2026",
        end: "01.08.2026",
        status: "active",
      },
      {
        id: 2,
        direction: "Design",
        name: "UI/UX Design",
        teacher: "Shakhlo Razzaqova",
        start: "15.02.2026",
        end: "15.08.2026",
        status: "active",
      },
    ],
    payments: [
      {
        id: 1,
        amount: 700000,
        status: "paid",
        method: "Click",
        date: "2026-02-15 09:00",
        group: "UI/UX Design",
      },
    ],
  },
  {
    id: 6,
    familya: "Nazarov",
    name: "Sherzod Nazarov",
    login: "sherzod",
    password: "12345",
    email: "sherzod@isouz.com",
    phone: "+998 90 678 90 12",
    avatar: "S",
    color: "#f97316",
    coin: 430,
    groups: [
      {
        id: 1,
        direction: "Frontend",
        name: "JavaScript Bootcamp",
        teacher: "Akmal Karimov",
        start: "01.02.2026",
        end: "01.08.2026",
        status: "active",
      },
      {
        id: 2,
        direction: "Backend",
        name: "Python 101",
        teacher: "Jasur Nazarov",
        start: "01.01.2026",
        end: "01.07.2026",
        status: "active",
      },
    ],
    payments: [
      {
        id: 1,
        amount: 400000,
        status: "unpaid",
        method: "Naqd",
        date: "2026-03-01 00:00",
        group: "Python 101",
      },
    ],
  },
  {
    id: 7,
    familya: "Yusupova",
    name: "Nilufar Yusupova",
    login: "nilufar",
    password: "12345",
    email: "nilufar@isouz.com",
    phone: "+998 91 789 01 23",
    avatar: "N",
    color: "#ec4899",
    coin: 770,
    groups: [
      {
        id: 1,
        direction: "Frontend",
        name: "Frontend 301",
        teacher: "Akmal Karimov",
        start: "01.03.2026",
        end: "01.09.2026",
        status: "active",
      },
      {
        id: 2,
        direction: "Design",
        name: "UI/UX Design",
        teacher: "Shakhlo Razzaqova",
        start: "15.02.2026",
        end: "15.08.2026",
        status: "active",
      },
    ],
    payments: [
      {
        id: 1,
        amount: 800000,
        status: "paid",
        method: "Payme",
        date: "2026-03-01 14:00",
        group: "Frontend 301",
      },
    ],
  },
  {
    id: 8,
    familya: "Hasanov",
    name: "Otabek Hasanov",
    login: "otabek",
    password: "12345",
    email: "otabek@isouz.com",
    phone: "+998 93 890 12 34",
    avatar: "O",
    color: "#06b6d4",
    coin: 510,
    groups: [
      {
        id: 1,
        direction: "Frontend",
        name: "JavaScript Bootcamp",
        teacher: "Akmal Karimov",
        start: "01.02.2026",
        end: "01.08.2026",
        status: "active",
      },
      {
        id: 2,
        direction: "Mobile",
        name: "Flutter Dev",
        teacher: "Bekzod Tursunov",
        start: "01.03.2026",
        end: "01.09.2026",
        status: "active",
      },
    ],
    payments: [
      {
        id: 1,
        amount: 900000,
        status: "paid",
        method: "Click",
        date: "2026-03-05 10:00",
        group: "Flutter Dev",
      },
    ],
  },
  {
    id: 9,
    familya: "Sobirov",
    name: "Doniyor Sobirov",
    login: "doniyor",
    password: "12345",
    email: "doniyor@isouz.com",
    phone: "+998 94 901 23 45",
    avatar: "D",
    color: "#84cc16",
    coin: 390,
    groups: [
      {
        id: 1,
        direction: "Frontend",
        name: "JavaScript Bootcamp",
        teacher: "Akmal Karimov",
        start: "01.02.2026",
        end: "01.08.2026",
        status: "active",
      },
      {
        id: 2,
        direction: "Backend",
        name: "Node.js Advanced",
        teacher: "Jasur Nazarov",
        start: "15.01.2026",
        end: "15.07.2026",
        status: "active",
      },
    ],
    payments: [
      {
        id: 1,
        amount: 850000,
        status: "paid",
        method: "Naqd",
        date: "2026-01-20 16:00",
        group: "Node.js Advanced",
      },
    ],
  },
  {
    id: 10,
    familya: "Mirzayeva",
    name: "Kamola Mirzayeva",
    login: "kamola",
    password: "12345",
    email: "kamola@isouz.com",
    phone: "+998 95 012 34 56",
    avatar: "K",
    color: "#a855f7",
    coin: 1120,
    groups: [
      {
        id: 1,
        direction: "Frontend",
        name: "JavaScript Bootcamp",
        teacher: "Akmal Karimov",
        start: "01.02.2026",
        end: "01.08.2026",
        status: "active",
      },
      {
        id: 2,
        direction: "Design",
        name: "UI/UX Design",
        teacher: "Shakhlo Razzaqova",
        start: "15.02.2026",
        end: "15.08.2026",
        status: "active",
      },
    ],
    payments: [
      {
        id: 1,
        amount: 800000,
        status: "paid",
        method: "Payme",
        date: "2026-02-05 08:30",
        group: "JavaScript Bootcamp",
      },
    ],
  },
  {
    id: 11,
    familya: "Tursunov",
    name: "Asilbek Tursunov",
    login: "asilbek",
    password: "12345",
    email: "asilbek@isouz.com",
    phone: "+998 90 123 11 22",
    avatar: "A",
    color: "#3b82f6",
    coin: 670,
    groups: [
      {
        id: 1,
        direction: "Frontend",
        name: "JavaScript Bootcamp",
        teacher: "Akmal Karimov",
        start: "01.02.2026",
        end: "01.08.2026",
        status: "active",
      },
      {
        id: 2,
        direction: "Mobile",
        name: "Flutter Dev",
        teacher: "Bekzod Tursunov",
        start: "01.03.2026",
        end: "01.09.2026",
        status: "active",
      },
    ],
    payments: [
      {
        id: 1,
        amount: 900000,
        status: "paid",
        method: "Click",
        date: "2026-03-03 13:00",
        group: "Flutter Dev",
      },
    ],
  },
  {
    id: 12,
    familya: "Qodirov",
    name: "Umid Qodirov",
    login: "umid",
    password: "12345",
    email: "umid@isouz.com",
    phone: "+998 91 234 22 33",
    avatar: "U",
    color: "#14b8a6",
    coin: 290,
    groups: [
      {
        id: 1,
        direction: "Frontend",
        name: "JavaScript Bootcamp",
        teacher: "Akmal Karimov",
        start: "01.02.2026",
        end: "01.08.2026",
        status: "active",
      },
      {
        id: 2,
        direction: "Marketing",
        name: "Marketing Pro",
        teacher: "Dilnoza Yusupova",
        start: "01.02.2026",
        end: "01.08.2026",
        status: "active",
      },
    ],
    payments: [
      {
        id: 1,
        amount: 600000,
        status: "unpaid",
        method: "Click",
        date: "2026-03-10 00:00",
        group: "Marketing Pro",
      },
    ],
  },
  {
    id: 13,
    familya: "Xolmatova",
    name: "Feruza Xolmatova",
    login: "feruza",
    password: "12345",
    email: "feruza@isouz.com",
    phone: "+998 93 345 33 44",
    avatar: "F",
    color: "#f43f5e",
    coin: 830,
    groups: [
      {
        id: 1,
        direction: "Frontend",
        name: "JavaScript Bootcamp",
        teacher: "Akmal Karimov",
        start: "01.02.2026",
        end: "01.08.2026",
        status: "active",
      },
      {
        id: 2,
        direction: "SMM",
        name: "SMM Pro",
        teacher: "Dilnoza Yusupova",
        start: "15.01.2026",
        end: "15.07.2026",
        status: "active",
      },
    ],
    payments: [
      {
        id: 1,
        amount: 600000,
        status: "paid",
        method: "Payme",
        date: "2026-01-18 09:30",
        group: "SMM Pro",
      },
    ],
  },
  {
    id: 14,
    familya: "Normatov",
    name: "Zafar Normatov",
    login: "zafar",
    password: "12345",
    email: "zafar@isouz.com",
    phone: "+998 94 456 44 55",
    avatar: "Z",
    color: "#0ea5e9",
    coin: 460,
    groups: [
      {
        id: 1,
        direction: "Frontend",
        name: "JavaScript Bootcamp",
        teacher: "Akmal Karimov",
        start: "01.02.2026",
        end: "01.08.2026",
        status: "active",
      },
      {
        id: 2,
        direction: "Backend",
        name: "Node.js Advanced",
        teacher: "Jasur Nazarov",
        start: "15.01.2026",
        end: "15.07.2026",
        status: "active",
      },
      {
        id: 3,
        direction: "Backend",
        name: "Python 101",
        teacher: "Jasur Nazarov",
        start: "01.01.2026",
        end: "01.07.2026",
        status: "active",
      },
    ],
    payments: [
      {
        id: 1,
        amount: 850000,
        status: "paid",
        method: "Naqd",
        date: "2026-02-10 11:00",
        group: "Node.js Advanced",
      },
    ],
  },
  {
    id: 15,
    familya: "Razzaqova",
    name: "Mohira Razzaqova",
    login: "mohira",
    password: "12345",
    email: "mohira@isouz.com",
    phone: "+998 95 567 55 66",
    avatar: "M",
    color: "#7c3aed",
    coin: 950,
    groups: [
      {
        id: 1,
        direction: "Frontend",
        name: "JavaScript Bootcamp",
        teacher: "Akmal Karimov",
        start: "01.02.2026",
        end: "01.08.2026",
        status: "active",
      },
      {
        id: 2,
        direction: "Design",
        name: "UI/UX Design",
        teacher: "Shakhlo Razzaqova",
        start: "15.02.2026",
        end: "15.08.2026",
        status: "active",
      },
    ],
    payments: [
      {
        id: 1,
        amount: 700000,
        status: "paid",
        method: "Click",
        date: "2026-02-16 10:00",
        group: "UI/UX Design",
      },
    ],
  },
  {
    id: 16,
    familya: "Ergashev",
    name: "Sanjar Ergashev",
    login: "sanjar",
    password: "12345",
    email: "sanjar@isouz.com",
    phone: "+998 90 678 66 77",
    avatar: "S",
    color: "#f59e0b",
    coin: 380,
    groups: [
      {
        id: 1,
        direction: "Frontend",
        name: "Frontend 301",
        teacher: "Akmal Karimov",
        start: "01.03.2026",
        end: "01.09.2026",
        status: "active",
      },
    ],
    payments: [
      {
        id: 1,
        amount: 800000,
        status: "pending",
        method: "Payme",
        date: "2026-03-08 00:00",
        group: "Frontend 301",
      },
    ],
  },
  {
    id: 17,
    familya: "Abdullayeva",
    name: "Zulfiya Abdullayeva",
    login: "zulfiya",
    password: "12345",
    email: "zulfiya@isouz.com",
    phone: "+998 91 789 77 88",
    avatar: "Z",
    color: "#10b981",
    coin: 1050,
    groups: [
      {
        id: 1,
        direction: "Frontend",
        name: "JavaScript Bootcamp",
        teacher: "Akmal Karimov",
        start: "01.02.2026",
        end: "01.08.2026",
        status: "active",
      },
    ],
    payments: [
      {
        id: 1,
        amount: 800000,
        status: "paid",
        method: "Click",
        date: "2026-02-03 08:00",
        group: "JavaScript Bootcamp",
      },
    ],
  },
  {
    id: 18,
    familya: "Mansurov",
    name: "Behzod Mansurov",
    login: "behzod",
    password: "12345",
    email: "behzod@isouz.com",
    phone: "+998 93 890 88 99",
    avatar: "B",
    color: "#6366f1",
    coin: 620,
    groups: [
      {
        id: 1,
        direction: "Frontend",
        name: "JavaScript Bootcamp",
        teacher: "Akmal Karimov",
        start: "01.02.2026",
        end: "01.08.2026",
        status: "active",
      },
      {
        id: 2,
        direction: "Mobile",
        name: "Flutter Dev",
        teacher: "Bekzod Tursunov",
        start: "01.03.2026",
        end: "01.09.2026",
        status: "active",
      },
      {
        id: 3,
        direction: "SMM",
        name: "SMM Pro",
        teacher: "Dilnoza Yusupova",
        start: "15.01.2026",
        end: "15.07.2026",
        status: "active",
      },
    ],
    payments: [
      {
        id: 1,
        amount: 900000,
        status: "paid",
        method: "Naqd",
        date: "2026-03-05 15:00",
        group: "Flutter Dev",
      },
    ],
  },
  {
    id: 19,
    familya: "Xasanova",
    name: "Lola Xasanova",
    login: "lola",
    password: "12345",
    email: "lola@isouz.com",
    phone: "+998 94 901 99 00",
    avatar: "L",
    color: "#ec4899",
    coin: 790,
    groups: [
      {
        id: 1,
        direction: "Frontend",
        name: "JavaScript Bootcamp",
        teacher: "Akmal Karimov",
        start: "01.02.2026",
        end: "01.08.2026",
        status: "active",
      },
      {
        id: 2,
        direction: "Marketing",
        name: "Marketing Pro",
        teacher: "Dilnoza Yusupova",
        start: "01.02.2026",
        end: "01.08.2026",
        status: "active",
      },
    ],
    payments: [
      {
        id: 1,
        amount: 600000,
        status: "paid",
        method: "Payme",
        date: "2026-02-20 12:00",
        group: "Marketing Pro",
      },
    ],
  },
  {
    id: 20,
    familya: "Qurbonov",
    name: "Ibrohim Qurbonov",
    login: "ibrohim",
    password: "12345",
    email: "ibrohim@isouz.com",
    phone: "+998 95 012 00 11",
    avatar: "I",
    color: "#0891b2",
    coin: 490,
    groups: [
      {
        id: 1,
        direction: "Frontend",
        name: "JavaScript Bootcamp",
        teacher: "Akmal Karimov",
        start: "01.02.2026",
        end: "01.08.2026",
        status: "active",
      },
      {
        id: 2,
        direction: "Backend",
        name: "Node.js Advanced",
        teacher: "Jasur Nazarov",
        start: "15.01.2026",
        end: "15.07.2026",
        status: "active",
      },
    ],
    payments: [
      {
        id: 1,
        amount: 850000,
        status: "paid",
        method: "Click",
        date: "2026-01-22 09:00",
        group: "Node.js Advanced",
      },
    ],
  },
];

export default DEFAULT_STUDENTS;