const DEFAULT_TEACHERS = [
  {
    id: 1,
    name: "Akmal Karimov",
    email: "akmal@isouz.com",
    phone: "+998 91 987 65 43",
    birthday: "15.05.1990",
    address: "Toshkent sh.",
    specialty: "Frontend dasturlash",
    experience: "5 yil",
    login: "akmal",
    password: "12345",
    avatar: "A",
    color: "#6366f1",
    groups: [
      {
        id: 1,
        direction: "Frontend Dasturlash",
        name: "JavaScript Bootcamp",
        teacher: "Akmal Karimov",
        start: "01.02.2026",
        end: "01.08.2026",
        status: "active",
      },
      {
        id: 2,
        direction: "Frontend Dasturlash",
        name: "Vue.js Pro",
        teacher: "Akmal Karimov",
        start: "10.03.2026",
        end: "10.09.2026",
        status: "active",
      },
    ],
  },

  {
    id: 2,
    name: "Dilnoza Yusupova",
    email: "dilnoza@isouz.com",
    phone: "+998 90 456 78 12",
    birthday: "22.08.1992",
    address: "Toshkent sh.",
    specialty: "SMM va Marketing",
    experience: "4 yil",
    login: "dilnoza",
    password: "12345",
    avatar: "D",
    color: "#ec4899",
    groups: [
      {
        id: 1,
        direction: "SMM & Marketing",
        name: "SMM Pro",
        teacher: "Dilnoza Yusupova",
        start: "15.01.2026",
        end: "15.07.2026",
        status: "active",
      },
      {
        id: 2,
        direction: "SMM & Marketing",
        name: "Targeting Master",
        teacher: "Dilnoza Yusupova",
        start: "01.03.2026",
        end: "01.09.2026",
        status: "active",
      },
    ],
  },

  {
    id: 3,
    name: "Jasur Nazarov",
    email: "jasur@isouz.com",
    phone: "+998 93 765 43 21",
    birthday: "10.11.1988",
    address: "Samarqand sh.",
    specialty: "Backend (Python / Node.js)",
    experience: "7 yil",
    login: "jasur_n",
    password: "12345",
    avatar: "J",
    color: "#10b981",
    groups: [
      {
        id: 1,
        direction: "Backend Development",
        name: "Python Backend",
        teacher: "Jasur Nazarov",
        start: "05.02.2026",
        end: "05.08.2026",
        status: "active",
      },
      {
        id: 2,
        direction: "Backend Development",
        name: "Node.js API Development",
        teacher: "Jasur Nazarov",
        start: "01.04.2026",
        end: "01.10.2026",
        status: "active",
      },
    ],
  },

  {
    id: 4,
    name: "Shakhlo Razzaqova",
    email: "shakhlo@isouz.com",
    phone: "+998 94 234 56 78",
    birthday: "03.02.1995",
    address: "Toshkent sh.",
    specialty: "UI/UX Design",
    experience: "6 yil",
    login: "shakhlo",
    password: "12345",
    avatar: "S",
    color: "#8b5cf6",
    groups: [
      {
        id: 1,
        direction: "Design",
        name: "UI/UX Design Bootcamp",
        teacher: "Shakhlo Razzaqova",
        start: "12.02.2026",
        end: "12.08.2026",
        status: "active",
      },
      {
        id: 2,
        direction: "Design",
        name: "Figma Masterclass",
        teacher: "Shakhlo Razzaqova",
        start: "01.03.2026",
        end: "01.09.2026",
        status: "active",
      },
    ],
  },

  {
    id: 5,
    name: "Bekzod Tursunov",
    email: "bekzod@isouz.com",
    phone: "+998 95 654 32 10",
    birthday: "18.09.1991",
    address: "Farg‘ona sh.",
    specialty: "Mobile Development (Flutter)",
    experience: "5 yil",
    login: "bekzod",
    password: "12345",
    avatar: "B",
    color: "#06b6d4",
    groups: [
      {
        id: 1,
        direction: "Mobile Development",
        name: "Flutter Bootcamp",
        teacher: "Bekzod Tursunov",
        start: "01.02.2026",
        end: "01.08.2026",
        status: "active",
      },
      {
        id: 2,
        direction: "Mobile Development",
        name: "Flutter Advanced",
        teacher: "Bekzod Tursunov",
        start: "15.03.2026",
        end: "15.09.2026",
        status: "active",
      },
    ],
  },

  {
    id: 6,
    name: "Azamat Qodirov",
    email: "azamat@isouz.com",
    phone: "+998 97 321 45 67",
    birthday: "27.01.1987",
    address: "Buxoro sh.",
    specialty: "DevOps va Cloud",
    experience: "8 yil",
    login: "azamat",
    password: "123",
    avatar: "A",
    color: "#f59e0b",
    groups: [
      {
        id: 1,
        direction: "DevOps",
        name: "Docker & Kubernetes",
        teacher: "Azamat Qodirov",
        start: "20.02.2026",
        end: "20.08.2026",
        status: "active",
      },
      {
        id: 2,
        direction: "Cloud Computing",
        name: "AWS Cloud Engineer",
        teacher: "Azamat Qodirov",
        start: "10.03.2026",
        end: "10.09.2026",
        status: "active",
      },
    ],
  },
];

export default DEFAULT_TEACHERS;
